<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IvoryCoastTaxComplianceSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Référentiel des règles DGI / CNPS / CMU
        $rules = [
            [
                'code' => 'dgi_tva_mensuelle',
                'titre' => 'TVA (Taxe sur la Valeur Ajoutée)',
                'administration' => 'DGI',
                'domaine' => 'fiscal',
                'base_legale' => 'Code Général des Impôts (CGI) Articles 100-150',
                'periodicite' => 'mensuelle',
                'jour_echeance' => 20,
                'mois_echeance' => null,
                'regimes_applicables' => json_encode(['RSI', 'RNI']),
                'secteurs_applicables' => json_encode(['all']),
                'severite' => 'bloquante',
                'description' => 'Déclaration et paiement mensuel de la TVA collectée et déductible sur e-impôts.',
                'penalite_formule' => '10% de majoration + 1% par mois d’intérêt de retard',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'dgi_its_mensuel',
                'titre' => 'ITS (Impôt sur Traitements et Salaires)',
                'administration' => 'DGI',
                'domaine' => 'fiscal',
                'base_legale' => 'CGI Articles 156-180 - Retenues à la source',
                'periodicite' => 'mensuelle',
                'jour_echeance' => 10,
                'mois_echeance' => null,
                'regimes_applicables' => json_encode(['all']),
                'secteurs_applicables' => json_encode(['all']),
                'severite' => 'bloquante',
                'description' => 'Reversement des retenues à la source sur salaires (IS, CN, IGR).',
                'penalite_formule' => '10% de majoration',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'cnps_cotisations_mensuelles',
                'titre' => 'Cotisations CNPS (PF, AT/MP, Retraite)',
                'administration' => 'CNPS',
                'domaine' => 'social',
                'base_legale' => 'Code de Prévoyance Sociale - Décret AT/MP',
                'periodicite' => 'mensuelle',
                'jour_echeance' => 15,
                'mois_echeance' => null,
                'regimes_applicables' => json_encode(['all']),
                'secteurs_applicables' => json_encode(['all']),
                'severite' => 'bloquante',
                'description' => 'Cotisations sociales patronales et salariales sur portail e-CNPS.',
                'penalite_formule' => '10% de majoration dès le premier mois + 3% par mois de retard',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'cmu_cotisations_mensuelles',
                'titre' => 'Couverture Maladie Universelle (CMU)',
                'administration' => 'CMU',
                'domaine' => 'social',
                'base_legale' => 'Loi n°2014-131 - Décret conjoint CNAM/CNPS',
                'periodicite' => 'mensuelle',
                'jour_echeance' => 15,
                'mois_echeance' => null,
                'regimes_applicables' => json_encode(['all']),
                'secteurs_applicables' => json_encode(['all']),
                'severite' => 'bloquante',
                'description' => 'Paiement de 1 000 FCFA part salariale + 1 000 FCFA part patronale par salarié affilié.',
                'penalite_formule' => '5 000 FCFA par salarié non régularisé + blocage attestation',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'cnps_disa_annuelle',
                'titre' => 'DISA (Déclaration Individuelle des Salaires Annuels)',
                'administration' => 'CNPS',
                'domaine' => 'social',
                'base_legale' => 'Code de Prévoyance Sociale Art. 21',
                'periodicite' => 'annuelle',
                'jour_echeance' => 30,
                'mois_echeance' => 3, // 30 mars
                'regimes_applicables' => json_encode(['all']),
                'secteurs_applicables' => json_encode(['all']),
                'severite' => 'bloquante',
                'description' => 'Dépôt dématérialisé nominatif de la masse salariale annuelle de l’exercice clos.',
                'penalite_formule' => 'Blocage immédiat de l’Attestation de Mise à Jour CNPS',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'dgi_patente_annuelle',
                'titre' => 'Contribution des patentes',
                'administration' => 'DGI',
                'domaine' => 'fiscal',
                'base_legale' => 'CGI Articles 200-230',
                'periodicite' => 'annuelle',
                'jour_echeance' => 30,
                'mois_echeance' => 4,
                'regimes_applicables' => json_encode(['all']),
                'secteurs_applicables' => json_encode(['all']),
                'severite' => 'majeure',
                'description' => 'Contribution assise sur le chiffre d’affaires et la valeur locative des locaux professionnels.',
                'penalite_formule' => '10% de majoration légale',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'inspection_chantier_btp',
                'titre' => 'Déclaration d’ouverture de chantier BTP',
                'administration' => 'COMMERCE',
                'domaine' => 'social',
                'base_legale' => 'Code du Travail & Pratique Inspection',
                'periodicite' => 'ponctuelle',
                'jour_echeance' => 28,
                'mois_echeance' => null,
                'regimes_applicables' => json_encode(['all']),
                'secteurs_applicables' => json_encode(['BTP']),
                'severite' => 'majeure',
                'description' => 'Formalisation obligatoire de l’ouverture d’un nouveau chantier de construction.',
                'penalite_formule' => 'Arrêt de chantier par l’Inspecteur du Travail',
                'actif' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('tax_rules')->upsert($rules, ['code']);

        // 2. Création de l'entreprise modèle fidèle à la maquette (Koffi BTP)
        $companyId = DB::table('companies')->insertGetId([
            'nom' => 'Établissements Koffi BTP',
            'forme_juridique' => 'SARL',
            'rccm' => 'CI-ABJ-2022-B-11409',
            'ncc' => '2204598 A',
            'secteur' => 'BTP',
            'regime_fiscal' => 'RSI',
            'ca_annuel' => 180_000_000,
            'ca_cumule_exercice' => 135_000_000,
            'effectif_salaries' => 14,
            'salaries_cmu_affilies' => 12,
            'masse_salariale_annuelle' => 48_000_000,
            'cga_adherent' => true,
            'cga_nom' => 'CGA BTP & Commerce Abidjan',
            'numero_cnps' => '118-2024-XXXX',
            'assujetti_tva' => true,
            'importateur' => false,
            'predicats' => json_encode([
                'employeur' => true,
                'chantiers_btp' => true,
                'cga' => true,
                'adherent_cmu' => true,
            ]),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // 3. Obligations modèles (faisant écho à la maquette)
        $obligations = [
            [
                'company_id' => $companyId,
                'rule_code' => 'dgi_tva_mensuelle',
                'titre' => 'Déclaration TVA — Août 2026',
                'description' => 'Échéance dépassée le 20/08/2026 · Télédéclaration DGI e-impôts',
                'domaine' => 'fiscal',
                'statut' => 'en_retard',
                'date_echeance' => '2026-08-20',
                'mois_groupe' => 'Août 2026',
                'montant_principal' => 450_000,
                'majoration_estimee' => 45_000,
                'responsable' => 'Alex Koffi',
                'severite' => 'bloquante',
                'fiche_instruction_id' => 'tva',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => $companyId,
                'rule_code' => 'cnps_cotisations_mensuelles',
                'titre' => 'Cotisation CNPS — Août 2026',
                'description' => 'Échéance dépassée le 15/08/2026 · 14 salariés déclarés',
                'domaine' => 'social',
                'statut' => 'en_retard',
                'date_echeance' => '2026-08-15',
                'mois_groupe' => 'Août 2026',
                'montant_principal' => 220_000,
                'majoration_estimee' => 22_000,
                'responsable' => 'Comptable interne',
                'severite' => 'bloquante',
                'fiche_instruction_id' => 'cnps',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => $companyId,
                'rule_code' => 'dgi_its_mensuel',
                'titre' => 'Déclaration ITS — Septembre 2026',
                'description' => 'Échéance le 10/09/2026 · Retenues à la source sur salaires',
                'domaine' => 'fiscal',
                'statut' => 'imminente',
                'date_echeance' => '2026-09-10',
                'mois_groupe' => 'Septembre 2026',
                'montant_principal' => 140_000,
                'majoration_estimee' => 0,
                'responsable' => 'Alex Koffi',
                'severite' => 'majeure',
                'fiche_instruction_id' => 'its',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => $companyId,
                'rule_code' => 'cnps_cotisations_mensuelles',
                'titre' => 'Déclaration CNPS — Septembre 2026',
                'description' => 'Échéance le 15/09/2026 · Télédéclaration e-CNPS mensuelle',
                'domaine' => 'social',
                'statut' => 'imminente',
                'date_echeance' => '2026-09-15',
                'mois_groupe' => 'Septembre 2026',
                'montant_principal' => 275_000,
                'majoration_estimee' => 0,
                'responsable' => 'Comptable interne',
                'severite' => 'bloquante',
                'fiche_instruction_id' => 'cnps',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => $companyId,
                'rule_code' => 'inspection_chantier_btp',
                'titre' => 'Déclaration d\'ouverture de chantier',
                'description' => 'Échéance le 28/09/2026 · Nouveau chantier Cocody Angré',
                'domaine' => 'social',
                'statut' => 'imminente',
                'date_echeance' => '2026-09-28',
                'mois_groupe' => 'Septembre 2026',
                'montant_principal' => 0,
                'majoration_estimee' => 0,
                'responsable' => 'Chef de chantier',
                'severite' => 'majeure',
                'fiche_instruction_id' => 'chantier',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => $companyId,
                'rule_code' => 'dgi_patente_annuelle',
                'titre' => 'Poinçonnage annuel des balances',
                'description' => 'Effectué et validé le 02/09/2026 · Vignette verte apposée',
                'domaine' => 'commerce',
                'statut' => 'accomplie',
                'date_echeance' => '2026-09-02',
                'mois_groupe' => 'Septembre 2026',
                'montant_principal' => 35_000,
                'majoration_estimee' => 0,
                'responsable' => 'Alex Koffi',
                'severite' => 'mineure',
                'fiche_instruction_id' => 'metro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => $companyId,
                'rule_code' => 'greffe_etats_financiers',
                'titre' => 'Dépôt des états financiers OHADA',
                'description' => 'Échéance annuelle le 30/04/2027 · Greffe Tribunal de Commerce',
                'domaine' => 'administratif',
                'statut' => 'a_venir',
                'date_echeance' => '2027-04-30',
                'mois_groupe' => 'Échéances annuelles',
                'montant_principal' => 50_000,
                'majoration_estimee' => 0,
                'responsable' => 'Expert-comptable',
                'severite' => 'majeure',
                'fiche_instruction_id' => 'ohada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('compliance_obligations')->insert($obligations);
    }
}
